version: "3.8"

services:
  nuxt-app:
    build: .
    ports:
      - "3000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "npm", "run", "start" ]
